FROM centos:7

MAINTAINER Jacob Salmela <jacob.salmela@pi-hole.net>

RUN yum install -y https://copr-be.cloud.fedoraproject.org/results/@spacewalkproject/spacewalk-2.8/epel-7-x86_64/00736372-spacewalk-repo/spacewalk-repo-2.8-11.el7.centos.noarch.rpm \
        https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
        yum-utils && \
        yum clean all

RUN yum -y install \
        spacewalk-postgresql \
        supervisor  \
        yum clean all

# Copy the spacewalk install answer file for an unattended install
COPY answerfile.txt /tmp/answerfile.txt

# Web interface, Jabber, DHCP/TFTP
EXPOSE 80 443 5222 68 69

USER root

#RUN spacewalk-setup --skip-fqdn-test --external-postgresql --skip-db-population --skip-services-restart --answer-file=/tmp/answerfile.txt

ADD supervisord.conf /etc/supervisord.d/supervisord.conf

ENTRYPOINT supervisord -c /etc/supervisord.d/supervisord.conf # && \
            # supervisorctl restart httpd && \
            # supervisorctl restart tomcat
