FROM centos:7

MAINTAINER Jacob Salmela <jacob.salmela@pi-hole.net>

RUN yum install -y https://copr-be.cloud.fedoraproject.org/results/%40spacewalkproject/spacewalk-2.10/epel-7-x86_64/01259466-spacewalk-repo/spacewalk-repo-2.10-8.el7.noarch.rpm \
        https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
        yum clean all

RUN yum -y install \
        spacewalk-postgresql \
        supervisor  \
        osad \
        wget \
        perl-Text-Unidecode \
        perl-Frontier-RPC-Client && \
        yum clean all

#RUN git clone https://github.com/liedekef/spacewalk_scripts.git /spacewalk-scripts

# Web interface, Jabber, DHCP/TFTP
EXPOSE 80 443 5222 68 69

USER root

# Copy scripts needed for syncing errata.  Perhaps better served as a PV, but this works for now
COPY centos-clone-errata-full.sh centos-clone-errata.sh epel-clone-errata.sh ya-errata-import.pl repo_sync.sh /spacewalk-scripts/

ENTRYPOINT supervisord -c /etc/supervisord.d/supervisord.conf
