apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spacewalk-html-pub-claim
  labels:
    app: spacewalk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
