---
apiVersion: v1
data:
  answerfile.txt: |
    admin-email = root@localhost
    ssl-set-cnames = spacewalk
    ssl-set-org = Spacewalk
    ssl-set-org-unit = spacewalk
    ssl-set-city = Minneapolis
    ssl-set-state = MN
    ssl-set-country = US
    ssl-password = spacewalk
    ssl-set-email = root@localhost
    ssl-config-sslvhost = Y
    db-backend=postgresql
    db-name=postgres
    db-user=spaceuser
    db-password=spacepw
    db-host=localhost
    db-port=5432
    enable-tftp=Y
kind: ConfigMap
metadata:
  name: spacewalk-answerfile
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spacewalk-errata-envs
data:
   SPACEWALK_USER: spaceman
   SPACEWALK_PASS: spaceman
