---
kind: Service
apiVersion: v1
metadata:
  name: spacewalk-web
  # annotations:
  #   service.alpha.kubernetes.io/app-protocols: '{"spacewalk-https":"HTTPS"}'
spec:
  selector:
    app: spacewalk-web
  ports:
  - name: spacewalk-http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: spacewalk-https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: spacewalk-jabber
    protocol: TCP
    port: 5222
    targetPort: 5222
  - name: spacewalk-dhcp
    protocol: TCP
    port: 68
    targetPort: 68
  - name: spacewalk-tftp
    protocol: TCP
    port: 69
    targetPort: 69
  type: NodePort
